// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module userdma_getinstream_Pipeline_VITIS_LOOP_48_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inStreamTop_TVALID,
        inbuf_din,
        inbuf_num_data_valid,
        inbuf_fifo_cap,
        inbuf_full_n,
        inbuf_write,
        incount47_din,
        incount47_num_data_valid,
        incount47_fifo_cap,
        incount47_full_n,
        incount47_write,
        in_len_V_load,
        inStreamTop_TDATA,
        inStreamTop_TREADY,
        inStreamTop_TKEEP,
        inStreamTop_TSTRB,
        inStreamTop_TUSER,
        inStreamTop_TLAST,
        sub_i_i52,
        in_s2m_len,
        tmp_user_V_out,
        tmp_user_V_out_ap_vld,
        icmp_ln1065_out,
        icmp_ln1065_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   inStreamTop_TVALID;
output  [32:0] inbuf_din;
input  [7:0] inbuf_num_data_valid;
input  [7:0] inbuf_fifo_cap;
input   inbuf_full_n;
output   inbuf_write;
output  [31:0] incount47_din;
input  [3:0] incount47_num_data_valid;
input  [3:0] incount47_fifo_cap;
input   incount47_full_n;
output   incount47_write;
input  [31:0] in_len_V_load;
input  [31:0] inStreamTop_TDATA;
output   inStreamTop_TREADY;
input  [3:0] inStreamTop_TKEEP;
input  [3:0] inStreamTop_TSTRB;
input  [6:0] inStreamTop_TUSER;
input  [0:0] inStreamTop_TLAST;
input  [32:0] sub_i_i52;
input  [31:0] in_s2m_len;
output  [3:0] tmp_user_V_out;
output   tmp_user_V_out_ap_vld;
output  [0:0] icmp_ln1065_out;
output   icmp_ln1065_out_ap_vld;

reg ap_idle;
reg inbuf_write;
reg incount47_write;
reg inStreamTop_TREADY;
reg tmp_user_V_out_ap_vld;
reg icmp_ln1065_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln72_reg_302;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1073_fu_252_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] width_count;
reg    inStreamTop_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    inbuf_blk_n;
reg    incount47_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln293_fu_168_p1;
reg   [3:0] trunc_ln293_reg_287;
wire   [0:0] icmp_ln1065_fu_189_p2;
reg   [0:0] icmp_ln1065_reg_292;
wire   [31:0] count_4_fu_214_p2;
reg   [31:0] count_4_reg_297;
wire   [0:0] icmp_ln72_fu_236_p2;
reg   [0:0] icmp_ln1073_reg_306;
wire   [31:0] select_ln1065_fu_200_p3;
reg   [31:0] count_fu_72;
wire    ap_loop_init;
reg   [31:0] empty_fu_76;
wire   [31:0] add_ln886_fu_220_p2;
reg    ap_block_pp0_stage0_01001;
wire  signed [31:0] sext_ln1065_fu_185_p0;
wire  signed [32:0] sext_ln1065_fu_185_p1;
wire  signed [31:0] add_ln67_fu_194_p0;
wire   [31:0] add_ln67_fu_194_p2;
wire   [27:0] tmp_fu_226_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 width_count = 32'd0;
#0 ap_done_reg = 1'b0;
end

userdma_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln72_fu_236_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1)))) begin
        count_fu_72 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln72_fu_236_p2 == 1'd0))) begin
        count_fu_72 <= count_4_fu_214_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            empty_fu_76 <= in_len_V_load;
        end else if (((icmp_ln1073_fu_252_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            empty_fu_76 <= add_ln886_fu_220_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        count_4_reg_297 <= count_4_fu_214_p2;
        icmp_ln1073_reg_306 <= icmp_ln1073_fu_252_p2;
        icmp_ln72_reg_302 <= icmp_ln72_fu_236_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1065_reg_292 <= icmp_ln1065_fu_189_p2;
        trunc_ln293_reg_287 <= trunc_ln293_fu_168_p1;
        width_count <= select_ln1065_fu_200_p3;
    end
end

always @ (*) begin
    if (((icmp_ln1073_fu_252_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1073_reg_306 == 1'd0))) begin
        icmp_ln1065_out_ap_vld = 1'b1;
    end else begin
        icmp_ln1065_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStreamTop_TDATA_blk_n = inStreamTop_TVALID;
    end else begin
        inStreamTop_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inStreamTop_TREADY = 1'b1;
    end else begin
        inStreamTop_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inbuf_blk_n = inbuf_full_n;
    end else begin
        inbuf_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inbuf_write = 1'b1;
    end else begin
        inbuf_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln72_reg_302 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        incount47_blk_n = incount47_full_n;
    end else begin
        incount47_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln72_reg_302 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        incount47_write = 1'b1;
    end else begin
        incount47_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1073_reg_306 == 1'd0))) begin
        tmp_user_V_out_ap_vld = 1'b1;
    end else begin
        tmp_user_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_fu_194_p0 = width_count;

assign add_ln67_fu_194_p2 = ($signed(add_ln67_fu_194_p0) + $signed(32'd1));

assign add_ln886_fu_220_p2 = (empty_fu_76 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln72_reg_302 == 1'd1) & (incount47_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inbuf_full_n == 1'b0) | (inStreamTop_TVALID == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln72_reg_302 == 1'd1) & (incount47_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inbuf_full_n == 1'b0) | (inStreamTop_TVALID == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln72_reg_302 == 1'd1) & (incount47_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inbuf_full_n == 1'b0) | (inStreamTop_TVALID == 1'b0))));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((inbuf_full_n == 1'b0) | (inStreamTop_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln72_reg_302 == 1'd1) & (incount47_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign count_4_fu_214_p2 = (count_fu_72 + 32'd1);

assign icmp_ln1065_fu_189_p2 = ((sext_ln1065_fu_185_p1 == sub_i_i52) ? 1'b1 : 1'b0);

assign icmp_ln1065_out = icmp_ln1065_reg_292;

assign icmp_ln1073_fu_252_p2 = ((add_ln886_fu_220_p2 < in_s2m_len) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_236_p2 = (($signed(tmp_fu_226_p4) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign inbuf_din = {{inStreamTop_TLAST}, {inStreamTop_TDATA}};

assign incount47_din = count_4_reg_297;

assign select_ln1065_fu_200_p3 = ((icmp_ln1065_fu_189_p2[0:0] == 1'b1) ? 32'd0 : add_ln67_fu_194_p2);

assign sext_ln1065_fu_185_p0 = width_count;

assign sext_ln1065_fu_185_p1 = sext_ln1065_fu_185_p0;

assign tmp_fu_226_p4 = {{count_4_fu_214_p2[31:4]}};

assign tmp_user_V_out = trunc_ln293_reg_287;

assign trunc_ln293_fu_168_p1 = inStreamTop_TUSER[3:0];

endmodule //userdma_getinstream_Pipeline_VITIS_LOOP_48_1
