// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="read_romcode_read_romcode,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=778,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1996,HLS_SYN_LUT=5098,HLS_VERSION=2022_2}" *)

module read_romcode (
        ap_clk,
        ap_rst_n,
        m_axi_BUS0_AWVALID,
        m_axi_BUS0_AWREADY,
        m_axi_BUS0_AWADDR,
        m_axi_BUS0_AWID,
        m_axi_BUS0_AWLEN,
        m_axi_BUS0_AWSIZE,
        m_axi_BUS0_AWBURST,
        m_axi_BUS0_AWLOCK,
        m_axi_BUS0_AWCACHE,
        m_axi_BUS0_AWPROT,
        m_axi_BUS0_AWQOS,
        m_axi_BUS0_AWREGION,
        m_axi_BUS0_AWUSER,
        m_axi_BUS0_WVALID,
        m_axi_BUS0_WREADY,
        m_axi_BUS0_WDATA,
        m_axi_BUS0_WSTRB,
        m_axi_BUS0_WLAST,
        m_axi_BUS0_WID,
        m_axi_BUS0_WUSER,
        m_axi_BUS0_ARVALID,
        m_axi_BUS0_ARREADY,
        m_axi_BUS0_ARADDR,
        m_axi_BUS0_ARID,
        m_axi_BUS0_ARLEN,
        m_axi_BUS0_ARSIZE,
        m_axi_BUS0_ARBURST,
        m_axi_BUS0_ARLOCK,
        m_axi_BUS0_ARCACHE,
        m_axi_BUS0_ARPROT,
        m_axi_BUS0_ARQOS,
        m_axi_BUS0_ARREGION,
        m_axi_BUS0_ARUSER,
        m_axi_BUS0_RVALID,
        m_axi_BUS0_RREADY,
        m_axi_BUS0_RDATA,
        m_axi_BUS0_RLAST,
        m_axi_BUS0_RID,
        m_axi_BUS0_RUSER,
        m_axi_BUS0_RRESP,
        m_axi_BUS0_BVALID,
        m_axi_BUS0_BREADY,
        m_axi_BUS0_BRESP,
        m_axi_BUS0_BID,
        m_axi_BUS0_BUSER,
        m_axi_BUS1_AWVALID,
        m_axi_BUS1_AWREADY,
        m_axi_BUS1_AWADDR,
        m_axi_BUS1_AWID,
        m_axi_BUS1_AWLEN,
        m_axi_BUS1_AWSIZE,
        m_axi_BUS1_AWBURST,
        m_axi_BUS1_AWLOCK,
        m_axi_BUS1_AWCACHE,
        m_axi_BUS1_AWPROT,
        m_axi_BUS1_AWQOS,
        m_axi_BUS1_AWREGION,
        m_axi_BUS1_AWUSER,
        m_axi_BUS1_WVALID,
        m_axi_BUS1_WREADY,
        m_axi_BUS1_WDATA,
        m_axi_BUS1_WSTRB,
        m_axi_BUS1_WLAST,
        m_axi_BUS1_WID,
        m_axi_BUS1_WUSER,
        m_axi_BUS1_ARVALID,
        m_axi_BUS1_ARREADY,
        m_axi_BUS1_ARADDR,
        m_axi_BUS1_ARID,
        m_axi_BUS1_ARLEN,
        m_axi_BUS1_ARSIZE,
        m_axi_BUS1_ARBURST,
        m_axi_BUS1_ARLOCK,
        m_axi_BUS1_ARCACHE,
        m_axi_BUS1_ARPROT,
        m_axi_BUS1_ARQOS,
        m_axi_BUS1_ARREGION,
        m_axi_BUS1_ARUSER,
        m_axi_BUS1_RVALID,
        m_axi_BUS1_RREADY,
        m_axi_BUS1_RDATA,
        m_axi_BUS1_RLAST,
        m_axi_BUS1_RID,
        m_axi_BUS1_RUSER,
        m_axi_BUS1_RRESP,
        m_axi_BUS1_BVALID,
        m_axi_BUS1_BREADY,
        m_axi_BUS1_BRESP,
        m_axi_BUS1_BID,
        m_axi_BUS1_BUSER,
        internal_bram_Addr_A,
        internal_bram_EN_A,
        internal_bram_WEN_A,
        internal_bram_Din_A,
        internal_bram_Dout_A,
        internal_bram_Clk_A,
        internal_bram_Rst_A,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_state2 = 18'd2;
parameter    ap_ST_fsm_state3 = 18'd4;
parameter    ap_ST_fsm_state4 = 18'd8;
parameter    ap_ST_fsm_state5 = 18'd16;
parameter    ap_ST_fsm_state6 = 18'd32;
parameter    ap_ST_fsm_state7 = 18'd64;
parameter    ap_ST_fsm_state8 = 18'd128;
parameter    ap_ST_fsm_state9 = 18'd256;
parameter    ap_ST_fsm_state10 = 18'd512;
parameter    ap_ST_fsm_state11 = 18'd1024;
parameter    ap_ST_fsm_state12 = 18'd2048;
parameter    ap_ST_fsm_state13 = 18'd4096;
parameter    ap_ST_fsm_state14 = 18'd8192;
parameter    ap_ST_fsm_state15 = 18'd16384;
parameter    ap_ST_fsm_state16 = 18'd32768;
parameter    ap_ST_fsm_state17 = 18'd65536;
parameter    ap_ST_fsm_state18 = 18'd131072;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS0_ID_WIDTH = 1;
parameter    C_M_AXI_BUS0_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUS0_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUS0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUS0_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUS0_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUS0_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUS0_USER_VALUE = 0;
parameter    C_M_AXI_BUS0_PROT_VALUE = 0;
parameter    C_M_AXI_BUS0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS1_ID_WIDTH = 1;
parameter    C_M_AXI_BUS1_ADDR_WIDTH = 64;
parameter    C_M_AXI_BUS1_DATA_WIDTH = 32;
parameter    C_M_AXI_BUS1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BUS1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BUS1_WUSER_WIDTH = 1;
parameter    C_M_AXI_BUS1_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUS1_BUSER_WIDTH = 1;
parameter    C_M_AXI_BUS1_USER_VALUE = 0;
parameter    C_M_AXI_BUS1_PROT_VALUE = 0;
parameter    C_M_AXI_BUS1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUS0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BUS1_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_BUS0_AWVALID;
input   m_axi_BUS0_AWREADY;
output  [C_M_AXI_BUS0_ADDR_WIDTH - 1:0] m_axi_BUS0_AWADDR;
output  [C_M_AXI_BUS0_ID_WIDTH - 1:0] m_axi_BUS0_AWID;
output  [7:0] m_axi_BUS0_AWLEN;
output  [2:0] m_axi_BUS0_AWSIZE;
output  [1:0] m_axi_BUS0_AWBURST;
output  [1:0] m_axi_BUS0_AWLOCK;
output  [3:0] m_axi_BUS0_AWCACHE;
output  [2:0] m_axi_BUS0_AWPROT;
output  [3:0] m_axi_BUS0_AWQOS;
output  [3:0] m_axi_BUS0_AWREGION;
output  [C_M_AXI_BUS0_AWUSER_WIDTH - 1:0] m_axi_BUS0_AWUSER;
output   m_axi_BUS0_WVALID;
input   m_axi_BUS0_WREADY;
output  [C_M_AXI_BUS0_DATA_WIDTH - 1:0] m_axi_BUS0_WDATA;
output  [C_M_AXI_BUS0_WSTRB_WIDTH - 1:0] m_axi_BUS0_WSTRB;
output   m_axi_BUS0_WLAST;
output  [C_M_AXI_BUS0_ID_WIDTH - 1:0] m_axi_BUS0_WID;
output  [C_M_AXI_BUS0_WUSER_WIDTH - 1:0] m_axi_BUS0_WUSER;
output   m_axi_BUS0_ARVALID;
input   m_axi_BUS0_ARREADY;
output  [C_M_AXI_BUS0_ADDR_WIDTH - 1:0] m_axi_BUS0_ARADDR;
output  [C_M_AXI_BUS0_ID_WIDTH - 1:0] m_axi_BUS0_ARID;
output  [7:0] m_axi_BUS0_ARLEN;
output  [2:0] m_axi_BUS0_ARSIZE;
output  [1:0] m_axi_BUS0_ARBURST;
output  [1:0] m_axi_BUS0_ARLOCK;
output  [3:0] m_axi_BUS0_ARCACHE;
output  [2:0] m_axi_BUS0_ARPROT;
output  [3:0] m_axi_BUS0_ARQOS;
output  [3:0] m_axi_BUS0_ARREGION;
output  [C_M_AXI_BUS0_ARUSER_WIDTH - 1:0] m_axi_BUS0_ARUSER;
input   m_axi_BUS0_RVALID;
output   m_axi_BUS0_RREADY;
input  [C_M_AXI_BUS0_DATA_WIDTH - 1:0] m_axi_BUS0_RDATA;
input   m_axi_BUS0_RLAST;
input  [C_M_AXI_BUS0_ID_WIDTH - 1:0] m_axi_BUS0_RID;
input  [C_M_AXI_BUS0_RUSER_WIDTH - 1:0] m_axi_BUS0_RUSER;
input  [1:0] m_axi_BUS0_RRESP;
input   m_axi_BUS0_BVALID;
output   m_axi_BUS0_BREADY;
input  [1:0] m_axi_BUS0_BRESP;
input  [C_M_AXI_BUS0_ID_WIDTH - 1:0] m_axi_BUS0_BID;
input  [C_M_AXI_BUS0_BUSER_WIDTH - 1:0] m_axi_BUS0_BUSER;
output   m_axi_BUS1_AWVALID;
input   m_axi_BUS1_AWREADY;
output  [C_M_AXI_BUS1_ADDR_WIDTH - 1:0] m_axi_BUS1_AWADDR;
output  [C_M_AXI_BUS1_ID_WIDTH - 1:0] m_axi_BUS1_AWID;
output  [7:0] m_axi_BUS1_AWLEN;
output  [2:0] m_axi_BUS1_AWSIZE;
output  [1:0] m_axi_BUS1_AWBURST;
output  [1:0] m_axi_BUS1_AWLOCK;
output  [3:0] m_axi_BUS1_AWCACHE;
output  [2:0] m_axi_BUS1_AWPROT;
output  [3:0] m_axi_BUS1_AWQOS;
output  [3:0] m_axi_BUS1_AWREGION;
output  [C_M_AXI_BUS1_AWUSER_WIDTH - 1:0] m_axi_BUS1_AWUSER;
output   m_axi_BUS1_WVALID;
input   m_axi_BUS1_WREADY;
output  [C_M_AXI_BUS1_DATA_WIDTH - 1:0] m_axi_BUS1_WDATA;
output  [C_M_AXI_BUS1_WSTRB_WIDTH - 1:0] m_axi_BUS1_WSTRB;
output   m_axi_BUS1_WLAST;
output  [C_M_AXI_BUS1_ID_WIDTH - 1:0] m_axi_BUS1_WID;
output  [C_M_AXI_BUS1_WUSER_WIDTH - 1:0] m_axi_BUS1_WUSER;
output   m_axi_BUS1_ARVALID;
input   m_axi_BUS1_ARREADY;
output  [C_M_AXI_BUS1_ADDR_WIDTH - 1:0] m_axi_BUS1_ARADDR;
output  [C_M_AXI_BUS1_ID_WIDTH - 1:0] m_axi_BUS1_ARID;
output  [7:0] m_axi_BUS1_ARLEN;
output  [2:0] m_axi_BUS1_ARSIZE;
output  [1:0] m_axi_BUS1_ARBURST;
output  [1:0] m_axi_BUS1_ARLOCK;
output  [3:0] m_axi_BUS1_ARCACHE;
output  [2:0] m_axi_BUS1_ARPROT;
output  [3:0] m_axi_BUS1_ARQOS;
output  [3:0] m_axi_BUS1_ARREGION;
output  [C_M_AXI_BUS1_ARUSER_WIDTH - 1:0] m_axi_BUS1_ARUSER;
input   m_axi_BUS1_RVALID;
output   m_axi_BUS1_RREADY;
input  [C_M_AXI_BUS1_DATA_WIDTH - 1:0] m_axi_BUS1_RDATA;
input   m_axi_BUS1_RLAST;
input  [C_M_AXI_BUS1_ID_WIDTH - 1:0] m_axi_BUS1_RID;
input  [C_M_AXI_BUS1_RUSER_WIDTH - 1:0] m_axi_BUS1_RUSER;
input  [1:0] m_axi_BUS1_RRESP;
input   m_axi_BUS1_BVALID;
output   m_axi_BUS1_BREADY;
input  [1:0] m_axi_BUS1_BRESP;
input  [C_M_AXI_BUS1_ID_WIDTH - 1:0] m_axi_BUS1_BID;
input  [C_M_AXI_BUS1_BUSER_WIDTH - 1:0] m_axi_BUS1_BUSER;
output  [31:0] internal_bram_Addr_A;
output   internal_bram_EN_A;
output  [3:0] internal_bram_WEN_A;
output  [31:0] internal_bram_Din_A;
input  [31:0] internal_bram_Dout_A;
output   internal_bram_Clk_A;
output   internal_bram_Rst_A;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg[31:0] internal_bram_Addr_A;
reg internal_bram_EN_A;
reg[3:0] internal_bram_WEN_A;
reg internal_bram_Rst_A;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] romcode;
wire   [63:0] romcode_to_PS;
wire   [31:0] cmd;
reg    BUS0_blk_n_AR;
wire    ap_CS_fsm_state10;
reg    BUS1_blk_n_AW;
wire    ap_CS_fsm_state2;
reg    BUS1_blk_n_B;
wire    ap_CS_fsm_state9;
reg   [31:0] cmd_read_reg_169;
wire   [31:0] cmd_read_read_fu_78_p2;
reg   [61:0] trunc_ln1_reg_173;
reg   [61:0] trunc_ln_reg_179;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_done;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_idle;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_ready;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWVALID;
wire   [63:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWADDR;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWLEN;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWSIZE;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWBURST;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWLOCK;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWCACHE;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWPROT;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWQOS;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWREGION;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WVALID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WDATA;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WSTRB;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WLAST;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WID;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARVALID;
wire   [63:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARADDR;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARLEN;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARSIZE;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARBURST;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARLOCK;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARCACHE;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARPROT;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARQOS;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARREGION;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_RREADY;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_BREADY;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_Addr_A;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_EN_A;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_WEN_A;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_Din_A;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_done;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_idle;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_ready;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWVALID;
wire   [63:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWADDR;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWLEN;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWSIZE;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWBURST;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWLOCK;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWCACHE;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWPROT;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWQOS;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWREGION;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WVALID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WDATA;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WSTRB;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WLAST;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WID;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARVALID;
wire   [63:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARADDR;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARID;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARLEN;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARSIZE;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARBURST;
wire   [1:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARLOCK;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARCACHE;
wire   [2:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARPROT;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARQOS;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARREGION;
wire   [0:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARUSER;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_RREADY;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_BREADY;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Addr_A;
wire    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_EN_A;
wire   [3:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_WEN_A;
wire   [31:0] grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Din_A;
wire    BUS0_AWREADY;
wire    BUS0_WREADY;
reg    BUS0_ARVALID;
wire    BUS0_ARREADY;
reg   [63:0] BUS0_ARADDR;
reg   [31:0] BUS0_ARLEN;
wire    BUS0_RVALID;
reg    BUS0_RREADY;
wire   [31:0] BUS0_RDATA;
wire   [10:0] BUS0_RFIFONUM;
wire    BUS0_BVALID;
reg    BUS1_AWVALID;
wire    BUS1_AWREADY;
reg   [63:0] BUS1_AWADDR;
reg   [31:0] BUS1_AWLEN;
reg    BUS1_WVALID;
wire    BUS1_WREADY;
wire    BUS1_ARREADY;
wire    BUS1_RVALID;
wire   [31:0] BUS1_RDATA;
wire   [10:0] BUS1_RFIFONUM;
wire    BUS1_BVALID;
reg    BUS1_BREADY;
reg    grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire  signed [63:0] sext_ln47_fu_149_p1;
wire  signed [63:0] sext_ln41_fu_159_p1;
reg    ap_block_state9;
reg    ap_block_state18_on_subcall_done;
reg   [17:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg = 1'b0;
#0 grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg = 1'b0;
end

read_romcode_read_romcode_Pipeline_VITIS_LOOP_47_2 grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start),
    .ap_done(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_done),
    .ap_idle(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_idle),
    .ap_ready(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_ready),
    .m_axi_BUS1_AWVALID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWVALID),
    .m_axi_BUS1_AWREADY(BUS1_AWREADY),
    .m_axi_BUS1_AWADDR(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWADDR),
    .m_axi_BUS1_AWID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWID),
    .m_axi_BUS1_AWLEN(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWLEN),
    .m_axi_BUS1_AWSIZE(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWSIZE),
    .m_axi_BUS1_AWBURST(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWBURST),
    .m_axi_BUS1_AWLOCK(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWLOCK),
    .m_axi_BUS1_AWCACHE(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWCACHE),
    .m_axi_BUS1_AWPROT(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWPROT),
    .m_axi_BUS1_AWQOS(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWQOS),
    .m_axi_BUS1_AWREGION(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWREGION),
    .m_axi_BUS1_AWUSER(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWUSER),
    .m_axi_BUS1_WVALID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WVALID),
    .m_axi_BUS1_WREADY(BUS1_WREADY),
    .m_axi_BUS1_WDATA(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WDATA),
    .m_axi_BUS1_WSTRB(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WSTRB),
    .m_axi_BUS1_WLAST(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WLAST),
    .m_axi_BUS1_WID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WID),
    .m_axi_BUS1_WUSER(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WUSER),
    .m_axi_BUS1_ARVALID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARVALID),
    .m_axi_BUS1_ARREADY(1'b0),
    .m_axi_BUS1_ARADDR(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARADDR),
    .m_axi_BUS1_ARID(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARID),
    .m_axi_BUS1_ARLEN(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARLEN),
    .m_axi_BUS1_ARSIZE(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARSIZE),
    .m_axi_BUS1_ARBURST(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARBURST),
    .m_axi_BUS1_ARLOCK(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARLOCK),
    .m_axi_BUS1_ARCACHE(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARCACHE),
    .m_axi_BUS1_ARPROT(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARPROT),
    .m_axi_BUS1_ARQOS(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARQOS),
    .m_axi_BUS1_ARREGION(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARREGION),
    .m_axi_BUS1_ARUSER(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_ARUSER),
    .m_axi_BUS1_RVALID(1'b0),
    .m_axi_BUS1_RREADY(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_RREADY),
    .m_axi_BUS1_RDATA(32'd0),
    .m_axi_BUS1_RLAST(1'b0),
    .m_axi_BUS1_RID(1'd0),
    .m_axi_BUS1_RFIFONUM(11'd0),
    .m_axi_BUS1_RUSER(1'd0),
    .m_axi_BUS1_RRESP(2'd0),
    .m_axi_BUS1_BVALID(BUS1_BVALID),
    .m_axi_BUS1_BREADY(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_BREADY),
    .m_axi_BUS1_BRESP(2'd0),
    .m_axi_BUS1_BID(1'd0),
    .m_axi_BUS1_BUSER(1'd0),
    .sext_ln47(trunc_ln1_reg_173),
    .internal_bram_Addr_A(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_Addr_A),
    .internal_bram_EN_A(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_EN_A),
    .internal_bram_WEN_A(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_WEN_A),
    .internal_bram_Din_A(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_Din_A),
    .internal_bram_Dout_A(internal_bram_Dout_A)
);

read_romcode_read_romcode_Pipeline_VITIS_LOOP_41_1 grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start),
    .ap_done(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_done),
    .ap_idle(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_idle),
    .ap_ready(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_ready),
    .m_axi_BUS0_AWVALID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWVALID),
    .m_axi_BUS0_AWREADY(1'b0),
    .m_axi_BUS0_AWADDR(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWADDR),
    .m_axi_BUS0_AWID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWID),
    .m_axi_BUS0_AWLEN(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWLEN),
    .m_axi_BUS0_AWSIZE(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWSIZE),
    .m_axi_BUS0_AWBURST(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWBURST),
    .m_axi_BUS0_AWLOCK(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWLOCK),
    .m_axi_BUS0_AWCACHE(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWCACHE),
    .m_axi_BUS0_AWPROT(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWPROT),
    .m_axi_BUS0_AWQOS(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWQOS),
    .m_axi_BUS0_AWREGION(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWREGION),
    .m_axi_BUS0_AWUSER(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_AWUSER),
    .m_axi_BUS0_WVALID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WVALID),
    .m_axi_BUS0_WREADY(1'b0),
    .m_axi_BUS0_WDATA(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WDATA),
    .m_axi_BUS0_WSTRB(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WSTRB),
    .m_axi_BUS0_WLAST(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WLAST),
    .m_axi_BUS0_WID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WID),
    .m_axi_BUS0_WUSER(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_WUSER),
    .m_axi_BUS0_ARVALID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARVALID),
    .m_axi_BUS0_ARREADY(BUS0_ARREADY),
    .m_axi_BUS0_ARADDR(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARADDR),
    .m_axi_BUS0_ARID(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARID),
    .m_axi_BUS0_ARLEN(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARLEN),
    .m_axi_BUS0_ARSIZE(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARSIZE),
    .m_axi_BUS0_ARBURST(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARBURST),
    .m_axi_BUS0_ARLOCK(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARLOCK),
    .m_axi_BUS0_ARCACHE(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARCACHE),
    .m_axi_BUS0_ARPROT(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARPROT),
    .m_axi_BUS0_ARQOS(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARQOS),
    .m_axi_BUS0_ARREGION(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARREGION),
    .m_axi_BUS0_ARUSER(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARUSER),
    .m_axi_BUS0_RVALID(BUS0_RVALID),
    .m_axi_BUS0_RREADY(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_RREADY),
    .m_axi_BUS0_RDATA(BUS0_RDATA),
    .m_axi_BUS0_RLAST(1'b0),
    .m_axi_BUS0_RID(1'd0),
    .m_axi_BUS0_RFIFONUM(BUS0_RFIFONUM),
    .m_axi_BUS0_RUSER(1'd0),
    .m_axi_BUS0_RRESP(2'd0),
    .m_axi_BUS0_BVALID(1'b0),
    .m_axi_BUS0_BREADY(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_BREADY),
    .m_axi_BUS0_BRESP(2'd0),
    .m_axi_BUS0_BID(1'd0),
    .m_axi_BUS0_BUSER(1'd0),
    .sext_ln41(trunc_ln_reg_179),
    .internal_bram_Addr_A(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Addr_A),
    .internal_bram_EN_A(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_EN_A),
    .internal_bram_WEN_A(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_WEN_A),
    .internal_bram_Din_A(grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Din_A),
    .internal_bram_Dout_A(32'd0)
);

read_romcode_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .romcode(romcode),
    .romcode_to_PS(romcode_to_PS),
    .cmd(cmd),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

read_romcode_BUS0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUS0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUS0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUS0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUS0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUS0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUS0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUS0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUS0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUS0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUS0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUS0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
BUS0_m_axi_U(
    .AWVALID(m_axi_BUS0_AWVALID),
    .AWREADY(m_axi_BUS0_AWREADY),
    .AWADDR(m_axi_BUS0_AWADDR),
    .AWID(m_axi_BUS0_AWID),
    .AWLEN(m_axi_BUS0_AWLEN),
    .AWSIZE(m_axi_BUS0_AWSIZE),
    .AWBURST(m_axi_BUS0_AWBURST),
    .AWLOCK(m_axi_BUS0_AWLOCK),
    .AWCACHE(m_axi_BUS0_AWCACHE),
    .AWPROT(m_axi_BUS0_AWPROT),
    .AWQOS(m_axi_BUS0_AWQOS),
    .AWREGION(m_axi_BUS0_AWREGION),
    .AWUSER(m_axi_BUS0_AWUSER),
    .WVALID(m_axi_BUS0_WVALID),
    .WREADY(m_axi_BUS0_WREADY),
    .WDATA(m_axi_BUS0_WDATA),
    .WSTRB(m_axi_BUS0_WSTRB),
    .WLAST(m_axi_BUS0_WLAST),
    .WID(m_axi_BUS0_WID),
    .WUSER(m_axi_BUS0_WUSER),
    .ARVALID(m_axi_BUS0_ARVALID),
    .ARREADY(m_axi_BUS0_ARREADY),
    .ARADDR(m_axi_BUS0_ARADDR),
    .ARID(m_axi_BUS0_ARID),
    .ARLEN(m_axi_BUS0_ARLEN),
    .ARSIZE(m_axi_BUS0_ARSIZE),
    .ARBURST(m_axi_BUS0_ARBURST),
    .ARLOCK(m_axi_BUS0_ARLOCK),
    .ARCACHE(m_axi_BUS0_ARCACHE),
    .ARPROT(m_axi_BUS0_ARPROT),
    .ARQOS(m_axi_BUS0_ARQOS),
    .ARREGION(m_axi_BUS0_ARREGION),
    .ARUSER(m_axi_BUS0_ARUSER),
    .RVALID(m_axi_BUS0_RVALID),
    .RREADY(m_axi_BUS0_RREADY),
    .RDATA(m_axi_BUS0_RDATA),
    .RLAST(m_axi_BUS0_RLAST),
    .RID(m_axi_BUS0_RID),
    .RUSER(m_axi_BUS0_RUSER),
    .RRESP(m_axi_BUS0_RRESP),
    .BVALID(m_axi_BUS0_BVALID),
    .BREADY(m_axi_BUS0_BREADY),
    .BRESP(m_axi_BUS0_BRESP),
    .BID(m_axi_BUS0_BID),
    .BUSER(m_axi_BUS0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(BUS0_ARVALID),
    .I_ARREADY(BUS0_ARREADY),
    .I_ARADDR(BUS0_ARADDR),
    .I_ARLEN(BUS0_ARLEN),
    .I_RVALID(BUS0_RVALID),
    .I_RREADY(BUS0_RREADY),
    .I_RDATA(BUS0_RDATA),
    .I_RFIFONUM(BUS0_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(BUS0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(BUS0_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(BUS0_BVALID),
    .I_BREADY(1'b0)
);

read_romcode_BUS1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BUS1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BUS1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BUS1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BUS1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BUS1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BUS1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BUS1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BUS1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BUS1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BUS1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BUS1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 11 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
BUS1_m_axi_U(
    .AWVALID(m_axi_BUS1_AWVALID),
    .AWREADY(m_axi_BUS1_AWREADY),
    .AWADDR(m_axi_BUS1_AWADDR),
    .AWID(m_axi_BUS1_AWID),
    .AWLEN(m_axi_BUS1_AWLEN),
    .AWSIZE(m_axi_BUS1_AWSIZE),
    .AWBURST(m_axi_BUS1_AWBURST),
    .AWLOCK(m_axi_BUS1_AWLOCK),
    .AWCACHE(m_axi_BUS1_AWCACHE),
    .AWPROT(m_axi_BUS1_AWPROT),
    .AWQOS(m_axi_BUS1_AWQOS),
    .AWREGION(m_axi_BUS1_AWREGION),
    .AWUSER(m_axi_BUS1_AWUSER),
    .WVALID(m_axi_BUS1_WVALID),
    .WREADY(m_axi_BUS1_WREADY),
    .WDATA(m_axi_BUS1_WDATA),
    .WSTRB(m_axi_BUS1_WSTRB),
    .WLAST(m_axi_BUS1_WLAST),
    .WID(m_axi_BUS1_WID),
    .WUSER(m_axi_BUS1_WUSER),
    .ARVALID(m_axi_BUS1_ARVALID),
    .ARREADY(m_axi_BUS1_ARREADY),
    .ARADDR(m_axi_BUS1_ARADDR),
    .ARID(m_axi_BUS1_ARID),
    .ARLEN(m_axi_BUS1_ARLEN),
    .ARSIZE(m_axi_BUS1_ARSIZE),
    .ARBURST(m_axi_BUS1_ARBURST),
    .ARLOCK(m_axi_BUS1_ARLOCK),
    .ARCACHE(m_axi_BUS1_ARCACHE),
    .ARPROT(m_axi_BUS1_ARPROT),
    .ARQOS(m_axi_BUS1_ARQOS),
    .ARREGION(m_axi_BUS1_ARREGION),
    .ARUSER(m_axi_BUS1_ARUSER),
    .RVALID(m_axi_BUS1_RVALID),
    .RREADY(m_axi_BUS1_RREADY),
    .RDATA(m_axi_BUS1_RDATA),
    .RLAST(m_axi_BUS1_RLAST),
    .RID(m_axi_BUS1_RID),
    .RUSER(m_axi_BUS1_RUSER),
    .RRESP(m_axi_BUS1_RRESP),
    .BVALID(m_axi_BUS1_BVALID),
    .BREADY(m_axi_BUS1_BREADY),
    .BRESP(m_axi_BUS1_BRESP),
    .BID(m_axi_BUS1_BID),
    .BUSER(m_axi_BUS1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(BUS1_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(BUS1_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(BUS1_RDATA),
    .I_RFIFONUM(BUS1_RFIFONUM),
    .I_AWVALID(BUS1_AWVALID),
    .I_AWREADY(BUS1_AWREADY),
    .I_AWADDR(BUS1_AWADDR),
    .I_AWLEN(BUS1_AWLEN),
    .I_WVALID(BUS1_WVALID),
    .I_WREADY(BUS1_WREADY),
    .I_WDATA(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WDATA),
    .I_WSTRB(grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WSTRB),
    .I_BVALID(BUS1_BVALID),
    .I_BREADY(BUS1_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_ready == 1'b1)) begin
            grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg <= 1'b1;
        end else if ((grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_ready == 1'b1)) begin
            grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cmd_read_reg_169 <= cmd;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (cmd_read_read_fu_78_p2 == 32'd1))) begin
        trunc_ln1_reg_173 <= {{romcode_to_PS[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (cmd_read_read_fu_78_p2 == 32'd0))) begin
        trunc_ln_reg_179 <= {{romcode[63:2]}};
    end
end

always @ (*) begin
    if (((1'b1 == BUS0_ARREADY) & (1'b1 == ap_CS_fsm_state10))) begin
        BUS0_ARADDR = sext_ln41_fu_159_p1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0)))) begin
        BUS0_ARADDR = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARADDR;
    end else begin
        BUS0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == BUS0_ARREADY) & (1'b1 == ap_CS_fsm_state10))) begin
        BUS0_ARLEN = 32'd1024;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0)))) begin
        BUS0_ARLEN = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARLEN;
    end else begin
        BUS0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == BUS0_ARREADY) & (1'b1 == ap_CS_fsm_state10))) begin
        BUS0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state17) | ((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0)))) begin
        BUS0_ARVALID = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_ARVALID;
    end else begin
        BUS0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0)))) begin
        BUS0_RREADY = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_m_axi_BUS0_RREADY;
    end else begin
        BUS0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        BUS0_blk_n_AR = m_axi_BUS0_ARREADY;
    end else begin
        BUS0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == BUS1_AWREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        BUS1_AWADDR = sext_ln47_fu_149_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        BUS1_AWADDR = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWADDR;
    end else begin
        BUS1_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == BUS1_AWREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        BUS1_AWLEN = 32'd1024;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        BUS1_AWLEN = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWLEN;
    end else begin
        BUS1_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == BUS1_AWREADY) & (1'b1 == ap_CS_fsm_state2))) begin
        BUS1_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        BUS1_AWVALID = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_AWVALID;
    end else begin
        BUS1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == BUS1_BVALID) & (cmd_read_reg_169 == 32'd1)) & (1'b1 == ap_CS_fsm_state9) & (cmd_read_reg_169 == 32'd1))) begin
        BUS1_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        BUS1_BREADY = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_BREADY;
    end else begin
        BUS1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        BUS1_WVALID = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_m_axi_BUS1_WVALID;
    end else begin
        BUS1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        BUS1_blk_n_AW = m_axi_BUS1_AWREADY;
    end else begin
        BUS1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (cmd_read_reg_169 == 32'd1))) begin
        BUS1_blk_n_B = m_axi_BUS1_BVALID;
    end else begin
        BUS1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == BUS0_ARREADY)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state18_on_subcall_done)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == BUS1_AWREADY)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == BUS1_BVALID) & (cmd_read_reg_169 == 32'd1))) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0))) begin
        internal_bram_Addr_A = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_bram_Addr_A = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_Addr_A;
    end else begin
        internal_bram_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0))) begin
        internal_bram_EN_A = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_bram_EN_A = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_internal_bram_EN_A;
    end else begin
        internal_bram_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) & (cmd_read_reg_169 == 32'd0))) begin
        internal_bram_WEN_A = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_WEN_A;
    end else begin
        internal_bram_WEN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (cmd_read_read_fu_78_p2 == 32'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~(cmd_read_read_fu_78_p2 == 32'd0) & ~(cmd_read_read_fu_78_p2 == 32'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (cmd_read_read_fu_78_p2 == 32'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == BUS1_AWREADY) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if ((~((1'b0 == BUS1_BVALID) & (cmd_read_reg_169 == 32'd1)) & ~(cmd_read_reg_169 == 32'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == BUS0_ARREADY) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_on_subcall_done = ((grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_done == 1'b0) & (cmd_read_reg_169 == 32'd0));
end

always @ (*) begin
    ap_block_state9 = ((1'b0 == BUS1_BVALID) & (cmd_read_reg_169 == 32'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmd_read_read_fu_78_p2 = cmd;

assign grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_ap_start_reg;

assign grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start = grp_read_romcode_Pipeline_VITIS_LOOP_47_2_fu_111_ap_start_reg;

assign internal_bram_Clk_A = ap_clk;

assign internal_bram_Din_A = grp_read_romcode_Pipeline_VITIS_LOOP_41_1_fu_120_internal_bram_Din_A;

always @ (*) begin
    internal_bram_Rst_A = ~ap_rst_n;
end

assign sext_ln41_fu_159_p1 = $signed(trunc_ln_reg_179);

assign sext_ln47_fu_149_p1 = $signed(trunc_ln1_reg_173);

endmodule //read_romcode
