set XPART xc7z020-clg400-1
set CSIM 0
set CSYNTH 1
set COSIM 0
set EXPORT_IP 1
set VIVADO_SYN 0
set VIVADO_IMPL 0
set XF_PROJ_ROOT "/home/tonyho/workspace_willy/caravel_fpga/project/vitis_hls_project/hls_output_pin/Makefile"
set CUR_DIR "/home/tonyho/workspace_willy/caravel_fpga/project/vitis_hls_project/hls_output_pin"
