-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity userdma_paralleltostreamwithburst is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_memory : IN STD_LOGIC_VECTOR (63 downto 0);
    in_en_clrsts : IN STD_LOGIC_VECTOR (0 downto 0);
    in_Img_width : IN STD_LOGIC_VECTOR (31 downto 0);
    in_m2s_len : IN STD_LOGIC_VECTOR (31 downto 0);
    outbuf_din : OUT STD_LOGIC_VECTOR (39 downto 0);
    outbuf_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    outbuf_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    outbuf_full_n : IN STD_LOGIC;
    outbuf_write : OUT STD_LOGIC;
    outcount48_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    outcount48_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    outcount48_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    outcount48_full_n : IN STD_LOGIC;
    outcount48_write : OUT STD_LOGIC;
    m2s_enb_clrsts_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    m2s_enb_clrsts_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    m2s_enb_clrsts_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    m2s_enb_clrsts_c_full_n : IN STD_LOGIC;
    m2s_enb_clrsts_c_write : OUT STD_LOGIC );
end;


architecture behav of userdma_paralleltostreamwithburst is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (21 downto 0) := "0000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (21 downto 0) := "0000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (21 downto 0) := "0000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (21 downto 0) := "0000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (21 downto 0) := "0000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (21 downto 0) := "0000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (21 downto 0) := "0001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (21 downto 0) := "0010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (21 downto 0) := "0100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (21 downto 0) := "1000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv33_1FFFFFFFF : STD_LOGIC_VECTOR (32 downto 0) := "111111111111111111111111111111111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal first : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal m2s_len : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal gmem1_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal outcount48_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal in_en_clrsts_read_read_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m2s_enb_clrsts_c_blk_n : STD_LOGIC;
    signal sub_i_i_fu_218_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_i_i_reg_364 : STD_LOGIC_VECTOR (32 downto 0);
    signal trunc_ln87_fu_250_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln87_reg_372 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_fu_254_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub_reg_377 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln107_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln107_reg_382 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1_reg_386 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_load_fu_191_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_idle : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_ready : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_din : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_write : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out_ap_vld : STD_LOGIC;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o_ap_vld : STD_LOGIC;
    signal ap_phi_mux_count_1_phi_fu_156_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_1_reg_151 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln100_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_58_phi_fu_167_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_58_reg_164 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state22 : BOOLEAN;
    signal grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal sext_ln107_fu_287_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal first_load_load_fu_198_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_allocacmp_m2s_len_load : STD_LOGIC_VECTOR (31 downto 0);
    signal idx_fu_98 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln132_fu_305_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln134_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal count_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_Img_width_cast_fu_214_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal shl_ln107_fu_266_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln107_fu_272_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln132_fu_301_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (21 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_condition_507 : BOOLEAN;
    signal ap_condition_298 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component userdma_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        outbuf_din : OUT STD_LOGIC_VECTOR (39 downto 0);
        outbuf_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
        outbuf_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
        outbuf_full_n : IN STD_LOGIC;
        outbuf_write : OUT STD_LOGIC;
        sext_ln107 : IN STD_LOGIC_VECTOR (61 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (30 downto 0);
        sub : IN STD_LOGIC_VECTOR (30 downto 0);
        in_m2s_len : IN STD_LOGIC_VECTOR (31 downto 0);
        sub_i_i : IN STD_LOGIC_VECTOR (32 downto 0);
        dec_phi_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        dec_phi_out_ap_vld : OUT STD_LOGIC;
        m2s_len_i : IN STD_LOGIC_VECTOR (31 downto 0);
        m2s_len_o : OUT STD_LOGIC_VECTOR (31 downto 0);
        m2s_len_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173 : component userdma_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start,
        ap_done => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done,
        ap_idle => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_idle,
        ap_ready => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_ready,
        m_axi_gmem1_AWVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM => m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        outbuf_din => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_din,
        outbuf_num_data_valid => ap_const_lv8_0,
        outbuf_fifo_cap => ap_const_lv8_0,
        outbuf_full_n => outbuf_full_n,
        outbuf_write => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_write,
        sext_ln107 => trunc_ln1_reg_386,
        trunc_ln => trunc_ln87_reg_372,
        sub => sub_reg_377,
        in_m2s_len => in_m2s_len,
        sub_i_i => sub_i_i_reg_364,
        dec_phi_out => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out,
        dec_phi_out_ap_vld => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out_ap_vld,
        m2s_len_i => m2s_len,
        m2s_len_o => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o,
        m2s_len_o_ap_vld => grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and ((icmp_ln134_fu_311_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_118_p2 = ap_const_lv1_1)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_ready = ap_const_logic_1)) then 
                    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_1_reg_151_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                if ((icmp_ln100_fu_238_p2 = ap_const_lv1_1)) then 
                    count_1_reg_151 <= ap_const_lv32_10;
                elsif ((icmp_ln100_fu_238_p2 = ap_const_lv1_0)) then 
                    count_1_reg_151 <= count_fu_102;
                end if;
            end if; 
        end if;
    end process;

    count_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_en_clrsts = ap_const_lv1_0)) then
                if ((ap_const_boolean_1 = ap_condition_298)) then 
                    count_fu_102 <= grp_load_fu_191_p1;
                elsif ((ap_const_boolean_1 = ap_condition_507)) then 
                    count_fu_102 <= ap_phi_mux_empty_58_phi_fu_167_p4;
                end if;
            end if; 
        end if;
    end process;

    empty_58_reg_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and (icmp_ln107_reg_382 = ap_const_lv1_1) and (in_en_clrsts = ap_const_lv1_0))) then 
                empty_58_reg_164 <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                empty_58_reg_164 <= grp_load_fu_191_p1;
            end if; 
        end if;
    end process;

    first_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (first_load_load_fu_198_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
                first <= ap_const_lv1_0;
            elsif (((icmp_ln100_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                first <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    idx_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_en_clrsts = ap_const_lv1_0)) then
                if ((ap_const_boolean_1 = ap_condition_298)) then 
                    idx_fu_98 <= ap_const_lv64_0;
                elsif ((ap_const_boolean_1 = ap_condition_507)) then 
                    idx_fu_98 <= add_ln132_fu_305_p2;
                end if;
            end if; 
        end if;
    end process;

    m2s_len_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (first_load_load_fu_198_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
                m2s_len <= in_m2s_len;
            elsif (((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state21))) then 
                m2s_len <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m2s_len_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln107_reg_382 <= icmp_ln107_fu_260_p2;
                sub_reg_377 <= sub_fu_254_p2;
                trunc_ln87_reg_372 <= trunc_ln87_fu_250_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then
                sub_i_i_reg_364 <= sub_i_i_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln107_fu_260_p2 = ap_const_lv1_1))) then
                trunc_ln1_reg_386 <= add_ln107_fu_272_p2(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axi_gmem1_ARREADY, in_en_clrsts, outcount48_full_n, m2s_enb_clrsts_c_full_n, ap_CS_fsm_state4, ap_CS_fsm_state22, in_en_clrsts_read_read_fu_118_p2, ap_CS_fsm_state2, icmp_ln107_fu_260_p2, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done, ap_CS_fsm_state21, icmp_ln134_fu_311_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts_read_read_fu_118_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln107_fu_260_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state4 => 
                if (((m_axi_gmem1_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state21) and (grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state21;
                end if;
            when ap_ST_fsm_state22 => 
                if ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and ((icmp_ln134_fu_311_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_118_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (icmp_ln134_fu_311_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state22) and (in_en_clrsts = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state22;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln107_fu_272_p2 <= std_logic_vector(unsigned(shl_ln107_fu_266_p2) + unsigned(in_memory));
    add_ln132_fu_305_p2 <= std_logic_vector(signed(sext_ln132_fu_301_p1) + signed(idx_fu_98));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, m2s_enb_clrsts_c_full_n)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;

    ap_ST_fsm_state21_blk_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done)
    begin
        if ((grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state21_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state21_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state22_blk_assign_proc : process(in_en_clrsts, outcount48_full_n)
    begin
        if (((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) then 
            ap_ST_fsm_state22_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state22_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(m_axi_gmem1_ARREADY)
    begin
        if ((m_axi_gmem1_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, m2s_enb_clrsts_c_full_n)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0));
    end process;


    ap_block_state22_assign_proc : process(in_en_clrsts, outcount48_full_n)
    begin
                ap_block_state22 <= ((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0));
    end process;


    ap_condition_298_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
                ap_condition_298 <= (not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_507_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state22, icmp_ln134_fu_311_p2)
    begin
                ap_condition_507 <= (not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (icmp_ln134_fu_311_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state22));
    end process;


    ap_done_assign_proc : process(ap_done_reg, in_en_clrsts, outcount48_full_n, ap_CS_fsm_state22, in_en_clrsts_read_read_fu_118_p2, icmp_ln134_fu_311_p2)
    begin
        if ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and ((icmp_ln134_fu_311_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_118_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_count_1_phi_fu_156_p4_assign_proc : process(ap_CS_fsm_state2, icmp_ln100_fu_238_p2, count_fu_102)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((icmp_ln100_fu_238_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_count_1_phi_fu_156_p4 <= ap_const_lv32_10;
            elsif ((icmp_ln100_fu_238_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_count_1_phi_fu_156_p4 <= count_fu_102;
            else 
                ap_phi_mux_count_1_phi_fu_156_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_count_1_phi_fu_156_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_empty_58_phi_fu_167_p4_assign_proc : process(in_en_clrsts, ap_CS_fsm_state22, icmp_ln107_reg_382, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out, empty_58_reg_164)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) and (icmp_ln107_reg_382 = ap_const_lv1_1) and (in_en_clrsts = ap_const_lv1_0))) then 
            ap_phi_mux_empty_58_phi_fu_167_p4 <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_dec_phi_out;
        else 
            ap_phi_mux_empty_58_phi_fu_167_p4 <= empty_58_reg_164;
        end if; 
    end process;


    ap_ready_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state22, in_en_clrsts_read_read_fu_118_p2, icmp_ln134_fu_311_p2)
    begin
        if ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and ((icmp_ln134_fu_311_p2 = ap_const_lv1_1) or (in_en_clrsts_read_read_fu_118_p2 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_m2s_len_load_assign_proc : process(ap_CS_fsm_state1, in_en_clrsts, in_m2s_len, m2s_len, first_load_load_fu_198_p1)
    begin
        if (((first_load_load_fu_198_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
            ap_sig_allocacmp_m2s_len_load <= in_m2s_len;
        else 
            ap_sig_allocacmp_m2s_len_load <= m2s_len;
        end if; 
    end process;

    first_load_load_fu_198_p1 <= first;

    gmem1_blk_n_AR_assign_proc : process(m_axi_gmem1_ARREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            gmem1_blk_n_AR <= m_axi_gmem1_ARREADY;
        else 
            gmem1_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    grp_load_fu_191_p1_assign_proc : process(ap_CS_fsm_state1, in_en_clrsts, m2s_len, ap_CS_fsm_state3, ap_sig_allocacmp_m2s_len_load)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_load_fu_191_p1 <= m2s_len;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (in_en_clrsts = ap_const_lv1_0))) then 
            grp_load_fu_191_p1 <= ap_sig_allocacmp_m2s_len_load;
        else 
            grp_load_fu_191_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_ap_start_reg;
    icmp_ln100_fu_238_p2 <= "1" when (signed(count_fu_102) > signed(ap_const_lv32_10)) else "0";
    icmp_ln107_fu_260_p2 <= "1" when (signed(ap_phi_mux_count_1_phi_fu_156_p4) > signed(ap_const_lv32_0)) else "0";
    icmp_ln134_fu_311_p2 <= "1" when (ap_phi_mux_empty_58_phi_fu_167_p4 = ap_const_lv32_0) else "0";
    in_Img_width_cast_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_Img_width),33));
    in_en_clrsts_read_read_fu_118_p2 <= in_en_clrsts;

    m2s_enb_clrsts_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m2s_enb_clrsts_c_blk_n <= m2s_enb_clrsts_c_full_n;
        else 
            m2s_enb_clrsts_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m2s_enb_clrsts_c_din <= in_en_clrsts;

    m2s_enb_clrsts_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, m2s_enb_clrsts_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or (m2s_enb_clrsts_c_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m2s_enb_clrsts_c_write <= ap_const_logic_1;
        else 
            m2s_enb_clrsts_c_write <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem1_ARADDR_assign_proc : process(m_axi_gmem1_ARREADY, ap_CS_fsm_state4, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARADDR, ap_CS_fsm_state20, ap_CS_fsm_state21, sext_ln107_fu_287_p1)
    begin
        if (((m_axi_gmem1_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_ARADDR <= sext_ln107_fu_287_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARADDR <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARADDR;
        else 
            m_axi_gmem1_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem1_ARBURST_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARBURST, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARBURST <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARBURST;
        else 
            m_axi_gmem1_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem1_ARCACHE_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARCACHE, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARCACHE <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARCACHE;
        else 
            m_axi_gmem1_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_ARID_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARID, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARID <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARID;
        else 
            m_axi_gmem1_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem1_ARLEN_assign_proc : process(m_axi_gmem1_ARREADY, ap_CS_fsm_state4, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLEN, count_1_reg_151, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((m_axi_gmem1_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_ARLEN <= count_1_reg_151;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARLEN <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLEN;
        else 
            m_axi_gmem1_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_gmem1_ARLOCK_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLOCK, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARLOCK <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARLOCK;
        else 
            m_axi_gmem1_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_gmem1_ARPROT_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARPROT, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARPROT <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARPROT;
        else 
            m_axi_gmem1_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem1_ARQOS_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARQOS, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARQOS <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARQOS;
        else 
            m_axi_gmem1_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_ARREGION_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARREGION, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARREGION <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARREGION;
        else 
            m_axi_gmem1_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_gmem1_ARSIZE_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARSIZE, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARSIZE <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARSIZE;
        else 
            m_axi_gmem1_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_gmem1_ARUSER_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARUSER, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARUSER <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARUSER;
        else 
            m_axi_gmem1_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_gmem1_ARVALID_assign_proc : process(m_axi_gmem1_ARREADY, ap_CS_fsm_state4, grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARVALID, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((m_axi_gmem1_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            m_axi_gmem1_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_ARVALID <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_ARVALID;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_RREADY, ap_CS_fsm_state20, ap_CS_fsm_state21)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            m_axi_gmem1_RREADY <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_m_axi_gmem1_RREADY;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    outbuf_din <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_din;

    outbuf_write_assign_proc : process(grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_write, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            outbuf_write <= grp_paralleltostreamwithburst_Pipeline_VITIS_LOOP_107_2_fu_173_outbuf_write;
        else 
            outbuf_write <= ap_const_logic_0;
        end if; 
    end process;


    outcount48_blk_n_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state22)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state22) and (in_en_clrsts = ap_const_lv1_0))) then 
            outcount48_blk_n <= outcount48_full_n;
        else 
            outcount48_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    outcount48_din <= count_1_reg_151;

    outcount48_write_assign_proc : process(in_en_clrsts, outcount48_full_n, ap_CS_fsm_state22)
    begin
        if ((not(((in_en_clrsts = ap_const_lv1_0) and (outcount48_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state22) and (in_en_clrsts = ap_const_lv1_0))) then 
            outcount48_write <= ap_const_logic_1;
        else 
            outcount48_write <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln107_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_386),64));

        sext_ln132_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(count_1_reg_151),64));

    shl_ln107_fu_266_p2 <= std_logic_vector(shift_left(unsigned(idx_fu_98),to_integer(unsigned('0' & ap_const_lv64_2(31-1 downto 0)))));
    sub_fu_254_p2 <= std_logic_vector(unsigned(trunc_ln87_fu_250_p1) + unsigned(ap_const_lv31_7FFFFFFF));
    sub_i_i_fu_218_p2 <= std_logic_vector(unsigned(in_Img_width_cast_fu_214_p1) + unsigned(ap_const_lv33_1FFFFFFFF));
    trunc_ln87_fu_250_p1 <= ap_phi_mux_count_1_phi_fu_156_p4(31 - 1 downto 0);
end behav;
