-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult_mmult_Pipeline_init is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arrayidx682_15_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_15_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_14_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_14_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_13_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_13_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_12_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_12_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_11_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_11_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_10_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_10_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_9_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_9_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_8_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_8_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_7_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_7_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_6_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_6_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_5_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_5_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_4_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_4_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_3_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_3_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_2_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_2_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_1_15_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_1_15_promoted_out_ap_vld : OUT STD_LOGIC;
    arrayidx682_15322_promoted_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    arrayidx682_15322_promoted_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mmult_mmult_Pipeline_init is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln52_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_fu_88 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_fu_282_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mmult_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component mmult_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln52_fu_276_p2 = ap_const_lv1_0)) then 
                    i_fu_88 <= add_ln52_fu_282_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_88 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln52_fu_282_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_state1, i_fu_88, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_88;
        end if; 
    end process;

    arrayidx682_10_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_10_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_10_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_10_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_11_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_11_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_11_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_11_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_12_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_12_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_12_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_12_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_13_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_13_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_13_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_13_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_14_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_14_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_14_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_14_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_15322_promoted_out <= ap_const_lv32_0;

    arrayidx682_15322_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_15322_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_15322_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_15_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_15_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_15_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_15_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_1_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_1_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_1_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_1_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_2_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_2_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_2_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_2_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_3_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_3_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_3_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_3_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_4_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_4_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_4_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_4_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_5_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_5_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_5_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_5_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_6_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_6_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_6_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_6_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_7_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_7_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_7_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_7_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_8_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_8_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_8_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_8_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    arrayidx682_9_15_promoted_out <= ap_const_lv32_0;

    arrayidx682_9_15_promoted_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, icmp_ln52_fu_276_p2, ap_start_int)
    begin
        if (((icmp_ln52_fu_276_p2 = ap_const_lv1_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            arrayidx682_9_15_promoted_out_ap_vld <= ap_const_logic_1;
        else 
            arrayidx682_9_15_promoted_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln52_fu_276_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv5_10) else "0";
end behav;
